### ISSUE TITLE
bubbleSort

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Excel231/onix-test2#5]
```
const bubbleSort = (currentBelts) => {
    for (let i = 0; i < currentBelts.length - 1; i++) {
        for (let j = 0; j < currentBelts.length - i - 1; j++) {
            if (currentBelts[j + 1].year < currentBelts[j].year) {
                let temp = currentBelts[j + 1].year;
                currentBelts[j + 1].year = currentBelts[j].year;
                currentBelts[j].year = temp;
            }
        }
    }
    return currentBelts;
}
```
Тут сразу несколько замечаний
1. Мутации, ты изменяешь входящий массив
2. Теперь чуть сложнее `currentBelts[j + 1].year = currentBelts[j].year;` вот этой строкой ты меняешь местами года, но не обьекты. И если у тебя был вот такой массив
```
{beltName: "The Ring", year: 2004},
{beltName: "WBO", year: 1995},
{beltName: "WBС", year: 2004}
```
То на выходе получился вот такой

<img width="252" alt="Снимок экрана 2022-05-20 в 18 41 01" src="https://user-images.githubusercontent.com/59687966/169563668-ddcc2328-e57f-4773-963d-74042bf57d5c.png">

Порядок тот же, даты разные)

**Comment by Excel231** [comment]
Solved
