### ISSUE TITLE
Регистрозависимость

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Excel231/onix-test2#6]
Когда называешь файлы и папки и импортируешь их, следи чтобы маленькие и большие буквы были одинаково как в импорте так и в названии. Иначе на многих операционных системах происходит вот такое
<img width="1596" alt="Снимок экрана 2022-06-01 в 22 18 22" src="https://user-images.githubusercontent.com/59687966/171484684-9f953e82-77db-46b1-b244-7cb664ca5c79.png">

**Comment by Excel231** [comment]
Привет. Как я понял, тут дело не совсем в регистрозависимости, а скорее в том, что я когда сортировал по фолдерам компоненты в один момент имел по два одинаковых фолдера, типа : "biography" и "Biography". Теперь оказалось, что гит всё ещё видит несуществующую папку в нижнем регистре, хотя её уже не существует. Вот что выдает консоль через git status, если удалить одну папку "Biography":
![webstorm64_GJW4tV1tzo](https://user-images.githubusercontent.com/79398191/172193172-62fbc075-deb1-4736-bc2b-b3fb5625b4ef.png)
